<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HP15S" failures="1" tests="1" name="Test" time="0.054" errors="0" timestamp="2022-07-27T15:28:55 IST">
  <testcase classname="TestNG.Test_9" name="P1" time="0.015">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [test] but found [test1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [test] but found [test1]
at TestNG.Test_9.P1(Test_9.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- P1 -->
</testsuite> <!-- Test -->
